In [3]:
import pandas as pd

In [7]:
df = pd.read_csv('FakeNewsNet.csv',engine='python')

In [8]:
df.head()

,title,news_url,source_domain,tweet_num,real
0,Kandi Burruss Explodes Over Rape Accusation on...,http://toofab.com/2017/05/08/real-housewives-a...,toofab.com,42,1
1,People's Choice Awards 2018: The best red carp...,https://www.today.com/style/see-people-s-choic...,www.today.com,0,1
2,Sophia Bush Sends Sweet Birthday Message to 'O...,https://www.etonline.com/news/220806_sophia_bu...,www.etonline.com,63,1
3,Colombian singer Maluma sparks rumours of inap...,https://www.dailymail.co.uk/news/article-33655...,www.dailymail.co.uk,20,1
4,Gossip Girl 10 Years Later: How Upper East Sid...,https://www.zerchoo.com/entertainment/gossip-g...,www.zerchoo.com,38,1

In [12]:
df.isnull().sum()

title              0
news_url         330
source_domain    330
tweet_num          0
real               0
dtype: int64

In [ ]:
df.dropna()

In [18]:
X=df.drop('source_domain',axis=1)

In [19]:
y=df['source_domain']

In [22]:
y

0                   toofab.com
1                www.today.com
2             www.etonline.com
3          www.dailymail.co.uk
4              www.zerchoo.com
                 ...
23191        www.express.co.uk
23192        hollywoodlife.com
23193        www.justjared.com
23194    www.intouchweekly.com
23195        www.billboard.com
Name: source_domain, Length: 23196, dtype: object

In [23]:
import tensorflow as tf

In [24]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [25]:
voc_size=5000

In [26]:
message = X.copy()

In [27]:
message['title'][1]

"People's Choice Awards 2018: The best red carpet looks"

In [28]:
import nltk
import re
from nltk.corpus import stopwords

In [29]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [33]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0,len(message)):
  review = re.sub('[^a-zA-Z]',' ',message['title'][i])
  review = review.lower()
  review = review.split()

  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)

In [36]:
onehot_rep = [one_hot(words,voc_size) for words in corpus]

In [ ]:
onehot_rep

In [38]:
sent=20
embed = pad_sequences(onehot_rep,padding='pre',maxlen=sent)

In [39]:
print(embed)

[[   0    0    0 ... 2927 1244 1258]
 [   0    0    0 ...   10 3256 1847]
 [   0    0    0 ... 1384 1832 3829]
 ...
 [   0    0    0 ...  811 3273 1376]
 [   0    0    0 ... 2946 2038 3395]
 [   0    0    0 ... 1659 1680 3795]]